<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="8eae36de-048c-4b0a-9726-8023adf41f78" name="Student@10266A-GEN-DEV- 2010-02-02 07:28:35" runUser="10266A-GEN-DEV-\Student" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="ec544e03-20d0-4280-bdbf-9f992f5801fd">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Student_10266A-GEN-DEV- 2010-02-02 07_28_35">
      <DeploymentItem filename="E:\Labfiles\Lab 4\Ex 2 - Detecting Exceptions\Starter\MatrixMultiplication\bin\Debug\MatrixMultiplication.exe" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2010-02-02T07:28:35.4175859-08:00" queuing="2010-02-02T07:28:35.4312578-08:00" start="2010-02-02T07:28:35.4527421-08:00" finish="2010-02-02T07:28:35.8726640-08:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="MatrixMultiplyTest2" storage="e:\labfiles\lab 4\ex 2 - detecting exceptions\starter\matrix unit test project\bin\debug\module 4 unit test project.dll" id="16e12141-9207-2540-ef3e-b656cbc6231c">
      <Execution id="2b3e563f-fe62-4a0f-8283-bf403b026a33" />
      <TestMethod codeBase="E:/Labfiles/Lab 4/Ex 2 - Detecting Exceptions/Starter/Matrix Unit Test Project/bin/Debug/Module 4 Unit Test Project.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="Lab4UnitTests.MatrixTest, Module 4 Unit Test Project, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="MatrixMultiplyTest2" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="16e12141-9207-2540-ef3e-b656cbc6231c" executionId="2b3e563f-fe62-4a0f-8283-bf403b026a33" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="2b3e563f-fe62-4a0f-8283-bf403b026a33" testId="16e12141-9207-2540-ef3e-b656cbc6231c" testName="MatrixMultiplyTest2" computerName="10266A-GEN-DEV-" duration="00:00:00.0175645" startTime="2010-02-02T07:28:35.4712968-08:00" endTime="2010-02-02T07:28:35.8345781-08:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="2b3e563f-fe62-4a0f-8283-bf403b026a33">
      <Output>
        <ErrorInfo>
          <Message>Exception of type 'Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException' was thrown.</Message>
          <StackTrace>   at Lab4UnitTests.MatrixTest.MatrixMultiplyTest2() in E:\Labfiles\Lab 4\Ex 2 - Detecting Exceptions\Starter\Matrix Unit Test Project\MatrixTest.cs:line 91
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>